import os


class Trait:

    def __init__(self, name, effects, remove_effects, bonus_points, face_value, color, expansion, is_dominant=False,
                 bonus_counted=False, playable=False):
        self.name = name
        self.effects = effects
        self.remove_effects = remove_effects
        self.bonus_points = bonus_points
        self.face_value = face_value
        self.color = color
        self.expansion = expansion
        self.is_dominant = is_dominant
        self.bonus_counted = bonus_counted
        self.playable = playable


traits = [Trait(name='Talons', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Purple', expansion='Dinolings'),
          Trait(name='Bark', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Green', expansion='Base'),
          Trait(name='Migratory', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Blue', expansion='Base'),
          Trait(name='Stone Skin', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Red', expansion='Base'),
          Trait(name='Destined', effects=[], remove_effects=[], bonus_points=None, face_value=4, color='Colorless', expansion='Mythlings'),
          Trait(name='Saliva',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=1, color='Blue', expansion='Base'),
          Trait(name='Teeth',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=1, color='Purple', expansion='Base'),
          Trait(name='Dreamer',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=1, color='Purple', expansion='Base'),
          Trait(name='Brute Strength',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}], bonus_points=None,
                face_value=4, color='Red', expansion='Base'),
          Trait(name='Mitochondrion',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=1, color='Colorless', expansion='Base'),
          Trait(name='Super Spreader',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'all', 'value': -1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'all', 'value': 1}}], bonus_points=None,
                face_value=2, color='Purple', expansion='Base'),
          Trait(name='Just',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=2, color='Colorless', expansion='Base'),
          Trait(name='Warm Blood',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 2}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -2}}], bonus_points=None,
                face_value=-1, color='Red', expansion='Base'),
          Trait(name='Fecundity',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}], bonus_points=None,
                face_value=1, color='Green', expansion='Base'),
          Trait(name='Ceratopsian Horns', effects=[], remove_effects=[], bonus_points=None, face_value=4, color='Green',
                expansion='Dinolings'),
          Trait(name='Big Ears', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Purple', expansion='Base'),
          Trait(name='Woody Stems', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Green', expansion='Base'),
          Trait(name='Antlers', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Red', expansion='Base'),
          Trait(name='Gills', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Blue', expansion='Base'),
          Trait(name='Fire Skin', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Red', expansion='Base'),
          Trait(name='Icy', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Blue', expansion='Mythlings'),
          Trait(name='Blubber', effects=[], remove_effects=[], bonus_points=None, face_value=4, color='Blue', expansion='Base'),
          Trait(name='Quick', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Red', expansion='Base'),
          Trait(name='Diaphanous Wings', effects=[], remove_effects=[], bonus_points=None, face_value=-1, color='Blue',
                expansion='Mythlings'),
          Trait(name='Confusion', effects=[], remove_effects=[], bonus_points=None, face_value=-2, color='Colorless', expansion='Base'),
          Trait(name='Spiny', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Blue', expansion='Base'),
          Trait(name='Leaves', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Green', expansion='Base'),
          Trait(name='Fine Motor Skills', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Purple',
                expansion='Base'),
          Trait(name='Fear', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Colorless', expansion='Base'),
          Trait(name='Nocturnal', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Purple', expansion='Base'),
          Trait(name='Adorable', effects=[], remove_effects=[], bonus_points=None, face_value=4, color='Purple', expansion='Base'),
          Trait(name='Fangs', effects=[], remove_effects=[], bonus_points=None, face_value=1, color='Red', expansion='Base'),
          Trait(name='Appealing', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Green', expansion='Base'),
          Trait(name='Deep Roots', effects=[], remove_effects=[], bonus_points=None, face_value=2, color='Green', expansion='Base'),
          Trait(name='Flatulence', effects=[], remove_effects=[], bonus_points=None, face_value=3, color='Colorless', expansion='Base'),
          Trait(name='Indomitable', is_dominant=True,
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -2}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 2}}], bonus_points=None,
                face_value=10, color='Red', expansion='Base'),
          Trait(name='Legendary', is_dominant=True,
                effects=[{'name': 'discard_hand', 'params': {'affected_players': 'self'}},
                         {'name': 'skip_stabilization', 'params': {'affected_players': 'self'}}],
                remove_effects=[], bonus_points=None,
                face_value=8, color='Blue', expansion='Base'),
          Trait(name='Kidney Chefs Toque', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Kidney Combover', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Kidney Elf Hat', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Kidney Party Hat', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Kidney Tiara', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Kidney Topper', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_kidney', 'params': {}}, face_value=None, color='Red',
                expansion='Base'),
          Trait(name='Swarm Fur', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_swarm', 'params': {}}, face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Swarm Horns', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_swarm', 'params': {}}, face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Swarm Mindless', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_swarm', 'params': {}}, face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Swarm Spots', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_swarm', 'params': {}}, face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Swarm Stripes', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_swarm', 'params': {}}, face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Heat Vision', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_for_every_color', 'params': {'color': 'Red', 'value': 1}},
                face_value=-1, color='Red',
                expansion='Base'),
          Trait(name='Sticky Secretions', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_for_every_color', 'params': {'color': 'Purple', 'value': 1}},
                face_value=-1, color='Purple',
                expansion='Base'),
          Trait(name='Egg Clusters', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_for_every_color', 'params': {'color': 'Blue', 'value': 1}},
                face_value=-1, color='Blue',
                expansion='Base'),
          Trait(name='Overgrowth', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_for_every_color', 'params': {'color': 'Green', 'value': 1}},
                face_value=-1, color='Green',
                expansion='Base'),
          Trait(name='Mindful', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_for_every_color', 'params': {'color': 'Colorless', 'value': 1}},
                face_value=-1, color='Colorless',
                expansion='Base'),
          Trait(name='Random Fertilization', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_gene_pool', 'params': {}},
                face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Altruistic', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_gene_pool', 'params': {}},
                face_value=None, color='Colorless',
                expansion='Base'),
          Trait(name='Hyper-Myelination', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_max_gene_pool', 'params': {}},
                face_value=None, color='Purple',
                expansion='Techlings'),
          Trait(name='Fortunate', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_number_cards_hand', 'params': {}},
                face_value=None, color='Green',
                expansion='Base'),
          Trait(name='Boredom', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_number_cards_hand', 'params': {'card_type': 'effect'}},
                face_value=None, color='Colorless',
                expansion='Base'),
          Trait(name='Dragon Heart', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_all_colors_trait_pile', 'params': {'value': 4}},
                face_value=1, color='Red',
                expansion='Mythlings'),
          Trait(name='Gratitude', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_number_colors', 'params': {'location': 'trait_pile', 'value': 1}},
                face_value=None, color='Colorless',
                expansion='Base'),
          Trait(name='Saudade', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_number_colors', 'params': {'location': 'hand', 'value': 1}},
                face_value=1, color='Colorless',
                expansion='Base'),
          Trait(name='Apex Predator', effects=[], remove_effects=[],
                bonus_points={'name': 'bonus_more_traits', 'params': {'value': 4}},
                face_value=4, color='Red',
                expansion='Base', is_dominant=True),
          Trait(name='Camouflage',
                effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': 1}}],
                remove_effects=[{'name': 'modify_gene_pool', 'params': {'affected_players': 'self', 'value': -1}}],
                bonus_points={'name': 'bonus_number_cards_hand', 'params': {}},
                face_value=1, color='Purple',
                expansion='Base', is_dominant=True),
          Trait(name='Immunity', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_negative_face_value', 'params': {'value': 2}},
                face_value=4, color='Blue',
                expansion='Base', is_dominant=True),
          Trait(name='Tiny', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_number_traits', 'params': {'value': -1}},
                face_value=17, color='Blue',
                expansion='Base', is_dominant=True),
          Trait(name='Tiny Arms', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_discard_expansion', 'params': {'expansion': 'Dinolings', 'value': 1}},
                face_value=-1, color='Red',
                expansion='Dinolings'),
          Trait(name='Serrated Teeth', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_discard_dominant', 'params': {'value': 1}},
                face_value=-1, color='Red',
                expansion='Dinolings'),
          Trait(name='Symbiosis', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_lowest_color', 'params': {'value': 2}},
                face_value=3, color='Green',
                expansion='Base', is_dominant=True),
          Trait(name='Cranial Crest', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_every_negative_discard', 'params': {'every': 3, 'value': 1}},
                face_value=1, color='Colorless',
                expansion='Dinolings'),
          Trait(name='Brave', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_dominant_hand', 'params': {'value': 2}},
                face_value=1, color='Red',
                expansion='Base'),
          Trait(name='Elven Ears', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_expansion_all_trait_piles',
                              'params': {'expansion': 'Mythlings', 'value': 1}},
                face_value=-1, color='Green',
                expansion='Mythlings'),
          Trait(name='Pollination', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_face_value', 'params': {'face_value': 1, 'value': 1}},
                face_value=1, color='Green',
                expansion='Base'),
          Trait(name='Branches', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_color_pair_opponents', 'params': {'color': 'Green', 'value': 1}},
                face_value=0, color='Green',
                expansion='Base'),
          Trait(name='Pack Behavior', effects=[],
                remove_effects=[],
                bonus_points={'name': 'bonus_color_pair', 'params': {'value': 1}},
                face_value=3, color='Green',
                expansion='Base', is_dominant=True)
          ]
